version: '3.3'

services:
  ubuntu-lamp-test:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu_lamp_osui_test
    ports:
      - "8080:80"
    restart: "no"
    volumes:
      - ./logs/ubuntu:/tmp/logs
    environment:
      - DISTRO_TYPE=ubuntu

  debian-lamp-test:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: debian_lamp_osui_test
    ports:
      - "8081:80"
    restart: "no"
    volumes:
      - ./logs/debian:/tmp/logs
    environment:
      - DISTRO_TYPE=debian

  centos-lamp-test:
    build:
      context: .
      dockerfile: Dockerfile.centos
    container_name: centos_lamp_osui_test
    ports:
      - "8082:80" # Nouveau port pour CentOS
    restart: "no"
    volumes:
      - ./logs/centos:/tmp/logs # Nouveau volume pour les logs CentOS
    environment:
      - DISTRO_TYPE=centos