FROM centos:latest

RUN yum update -y && \
    yum install -y sudo wget curl vim net-tools initscripts rsyslog && \
    yum clean all && \
    rm -rf /var/cache/yum/*

COPY systemctl-runner /usr/bin/systemctl-runner
RUN chmod +x /usr/bin/systemctl-runner

COPY apps/centos/install.sh /tmp/install.sh
RUN chmod +x /tmp/install.sh

CMD ["/usr/bin/systemctl-runner", "/tmp/install.sh", "--no-confirm"]

EXPOSE 80
